site_name: Documentación General
site_url: https://sitename.example
theme:
  name: material
  language: es
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  #icon:
    #logo: fontawesome/solid/w
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - navigation.footer
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

markdown_extensions:
  - attr_list
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 2 
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          #format: pymdownx.superfences.fence_div_format
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

extra:
  social:
    - icon: fontawesome/brands/mastodon 
      link: https://fosstodon.org/@squidfunk

extra_javascript:
  - assets/js/mermaid-export.js

# extra_javascript:
#   - https://unpkg.com/mermaid@10/dist/mermaid.min.js
#   - assets/js/copy-mermaid.js

extra_css:
  - assets/css/custom.css


# extra_css:
#   - assets/css/custom.css
# extra_javascript:
#   - https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js
#   - assets/js/copy-mermaid.js


# extra:
#   social:
#     - icon: simple/youtube
#       link: https://youtube.com/@james-willett
#     - icon: simple/linkedin
#       link: https://linkedin.com/in/willettjames

copyright: Copyright &copy; 2025 Miguel Ayte

nav:
  - Inicio: index.md

  - Procesos:
      - Data Warehouse:
          - ETL:
              - Carga de Ventas:
                  - Sin transformación: procesos/data-warehouse/etl/ventas/usp_jo_pos_dw_ventas_actualizar.md
                  - Con transformación: procesos/data-warehouse/etl/ventas/usp_jo_pos_dw_cubo_actualizar.md
          - Vistas:
              - vw_Producto: procesos/data-warehouse/vistas/ER-vw_Producto.md
              - vw_proyecciones_TY: procesos/data-warehouse/vistas/ER-vw_proyecciones_TY.md
          - Reportes:
              - ACH - Avance de Cuotas:
                  - Código: procesos/data-warehouse/reportes/ach/codigo.md
                  - Diagrama de Flujo: procesos/data-warehouse/reportes/ach/flujo.md
                  - Modelo Entidad-Relación: procesos/data-warehouse/reportes/ach/entidades.md
              - VDM - Ventas Diarias del Mes:
                  - Código: procesos/data-warehouse/reportes/vdm/codigo.md
                  - Diagrama de Flujo: procesos/data-warehouse/reportes/vdm/flujo.md
                  - Modelo Entidad-Relación: procesos/data-warehouse/reportes/vdm/entidades.md

  - Proyectos:
      - Mejora SP VDM:
          - Descripción: proyectos/mejora-sp-vdm/descripcion.md
          - Avances: proyectos/mejora-sp-vdm/avances.md
          - Documentos Técnicos:
              - FN nuevos: proyectos/mejora-sp-vdm/documentos-tecnicos/fn-nuevos.md
              - SP nuevos: proyectos/mejora-sp-vdm/documentos-tecnicos/sp-nuevos.md
              - Entidades nuevas: proyectos/mejora-sp-vdm/documentos-tecnicos/entidades-nuevas.md
              - Entidades modificadas: proyectos/mejora-sp-vdm/documentos-tecnicos/entidades-modificadas.md
              - Lista de Comprobación de Pruebas: proyectos/mejora-sp-vdm/documentos-tecnicos/lista-mejoras.md
              - Documentos de Pase a Producción: proyectos/mejora-sp-vdm/documentos-tecnicos/pase-produccion.md

  - Servicios:
      - Catálogo de Servicios: servicios/catalogo.md
      - Integraciones: servicios/integraciones.md

  - Aplicaciones:
      - Aplicación de Ventas: aplicaciones/ventas.md
      - Aplicación de Inventario: aplicaciones/inventario.md




# nav:
#   - Home: index.md
#   - Data Warehouse:
#       - ETL:
#           #- Carga de Catálogos:
#           - Carga de Ventas:
#               - DFD carga de ventas sin transformación: data-warehouse/etl/ventas/usp_jo_pos_dw_ventas_actualizar.md
#               - DFD carga de ventas con transformación: data-warehouse/etl/ventas/usp_jo_pos_dw_cubo_actualizar.md
#       - Vistas:
#           - vw_Producto: data-warehouse/vistas/ER-vw_Producto.md
#           - vw_proyecciones_TY: data-warehouse/vistas/ER-vw_proyecciones_TY.md
#       - Reportes:
#           - ACH Avance de Cuotas de Hoy:
#               - Código: data-warehouse/reportes/ach/codigo.md
#               - Diagrama de Flujo: data-warehouse/reportes/ach/flujo.md
#               - Modelo Entidad-Relación: data-warehouse/reportes/ach/entidades.md
#           - VDM Ventas Diarias del Mes:
#               - Código Actual: data-warehouse/reportes/vdm/codigo-actual.md
#               - Diagrama de Flujo: data-warehouse/reportes/vdm/flujo.md
#               - Modelo Entidad-Relación: data-warehouse/reportes/vdm/entidades.md
#               - Mejoras:
#                   - Lista de Mejoras: data-warehouse/reportes/vdm/mejoras/lista-mejoras.md
#                   - Nuevas Tablas Config: data-warehouse/reportes/vdm/mejoras/tablas-de-configuracion.md
#                   - Vista vw_Producto: data-warehouse/reportes/vdm/mejoras/vw_Producto.md
#                   - SP VDM_get_fechas: data-warehouse/reportes/vdm/mejoras/VDM_get_fechas.md
#                   - Modelo Entidad-Relación Mejorado: data-warehouse/reportes/vdm/mejoras/entidades-mejoradas.md


# nav:
#   - Home: index.md
#   - Data Warehouse:
#       - Introducción: data-warehouse/introduccion.md
#       - Modelado de Datos: data-warehouse/modelado-de-datos.md
#       - ETL: data-warehouse/etl.md
#       - Diagramas: 
#           - 1. Actualizar Costos SAP: data-warehouse/step-1-actualizar-costos-sap.md
#           - 2. Venta Diaria del Mes: data-warehouse/step-2-venta-diaria-del-mes.md

plugins:
  - search
#   - mermaid2
