site_name: Documentación General
site_url: https://sitename.example
theme:
  name: material
  language: es
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  #icon:
    #logo: fontawesome/solid/w
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - navigation.footer
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

extra:
  social:
    - icon: fontawesome/brands/mastodon 
      link: https://fosstodon.org/@squidfunk

# extra:
#   social:
#     - icon: simple/youtube
#       link: https://youtube.com/@james-willett
#     - icon: simple/linkedin
#       link: https://linkedin.com/in/willettjames

copyright: Copyright &copy; 2025 Miguel Ayte

nav:
  - Home: index.md
  - Data Warehouse:
      - ETL:
          - Introducción: proyectos/etl/index.md
          - ER vw_Producto: data-warehouse/etl/ER-vw_Producto.md
      - Reportes:
          - VDM:
              - Introducción: data-warehouse/reportes/vdm/index.md
              - Diagrama de Flujo: data-warehouse/reportes/vdm/flujo.md
              - Modelo Entidad-Relación: data-warehouse/reportes/vdm/entidades.md


# nav:
#   - Home: index.md
#   - Data Warehouse:
#       - Introducción: data-warehouse/introduccion.md
#       - Modelado de Datos: data-warehouse/modelado-de-datos.md
#       - ETL: data-warehouse/etl.md
#       - Diagramas: 
#           - 1. Actualizar Costos SAP: data-warehouse/step-1-actualizar-costos-sap.md
#           - 2. Venta Diaria del Mes: data-warehouse/step-2-venta-diaria-del-mes.md

plugins:
  - search
  - mermaid2
